# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recorder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recorder
  pod 'SpotlightLyrics'
  pod 'AudioKit', '~> 4.5'
end
